apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-deployment
  labels:
    app: reverse
spec:
  selector:
    matchLabels:
      app: reverse
  replicas: 2
  template:
    metadata:
      labels:
        app: reverse
    spec:
      containers:
      - name: reverse
        image: hrk/reverse-service:v1.0
        imagePullPolicy: Never
        ports:
        - name: reverse-service
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: reverse-service
spec:
  selector:
    app: reverse
  ports:
    - port: 3000
      targetPort: reverse-service
